// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: start.sql

package database

import (
	"context"
)

const addPlayer = `-- name: addPlayer :exec
update rounds 
set playerNum = playerNum + 1
`

func (q *Queries) addPlayer(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, addPlayer)
	return err
}

const clearGame = `-- name: clearGame :exec
delete from rounds
`

func (q *Queries) clearGame(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearGame)
	return err
}

const startGame = `-- name: startGame :one
insert into rounds (currentBet, totalBet, playerNum)
values (1, 1, 0)
returning currentbet, totalbet, playernum
`

func (q *Queries) startGame(ctx context.Context) (Round, error) {
	row := q.db.QueryRowContext(ctx, startGame)
	var i Round
	err := row.Scan(&i.Currentbet, &i.Totalbet, &i.Playernum)
	return i, err
}
